### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [imxblee/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by imxblee** [comment]
ok done, i have found a solution online to tackle this problem. By adding the below 
<meta name="viewport" content="width=device-width, initial-scale=1">  
into <head>.

**Comment by kenmazaika** [comment]
I just looked at your code and it looks great.  Thumbs up! :+1:
